cors:
  originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt:
    token:
      secret-key: 472D4B6150645367566B597033733676397924423F4528482B4D625165546857
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/estudo_spring?useTimezone=true&serverTimezone=UTC
    username: root
    password: salvador1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    flyway:
      baselineOnMigrate: true
      locations=classpath: db/migration
spring-doc:
  pathsToMatch:
   - /auth/**
   - /api/**/v1/**
  swagger-ui:
    use-root-path: true